# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9de3fdd797aa4501c9b49f486c46c6749c08ab262f394faa224a22e85cf868bd3c52b9948681a7d3dc1196e8bc739a31b3ebd67f05731cc6a4cea7da07edbb58

test:
  secret_key_base: e76559553f25f00ec586d85d4c68572b0943f09cffd386bd6838e2498e8a1eef66ba344ace27fbe82c1aaa09fb69e19849e4c2309c8492b424c77c8aa3c601cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
